version: '3'
services:
  url-shortener:
    build: 
      dockerfile: ./Dockerfile 
      context: ./
    ports:
      - 8080:8080
    links:
      - database
  database:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017
    command: mongod --smallfiles --logpath=/dev/null